# Generated by Django 3.2.6 on 2021-08-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_groceryitem_item_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='item_date',
            field=models.CharField(max_length=100),
        ),
    ]
